### PR TITLE
Accept options for scrollIntoView() via props.behavior

### PR DESCRIPTION
**Pull request by 1000ch**
Will be great with [Smooth Scroll behavior polyfill](http://iamdustan.com/smoothscroll/).

### CODE REVIEW

**Comment by rafrex** [comment]
Thanks for the PR.

At the time of creating this I decided not to implement options because they are only supported in Firefox. Is that still the case, or has support increased?

If we did include the options, it would be as the full options object, to allow for the `block` option as well. Not just the `behavior` string.

`prop-types` should stay as a dependency (and not become a peerDependency) because the React app using this lib may not have `prop-types` as a dependency. (Yes, `react-router` has it as a dependency, but that is not guaranteed to be the case forever).

**Comment by rafrex** [comment]
Also, don't pass down the behavior/scrollOptions prop to `Link`.

I'd be open to adding this for use with the polyfill even if browser support hasn't increased.

**Comment by 1000ch** [comment]
Thank you for considering, I would find other way 👌

**Comment by rafrex** [comment]
I wasn't saying no, but the code as submitted needed to be changed. Open to discussion...

**Comment by tehstun** [comment]
I second adding this feature, I came to the same result with it not working in chrome.

**Pull request closed without merging**
