### PR TITLE
Refactor component to be more extensible

### PR DESCRIPTION
**Pull request by jpbufe3**
This allows adding an `offset` and a `duration` property to the component and uses `jump.js` to handle the scrolling effects.

### CODE REVIEW

**Comment by jpbufe3** [comment]
@rafrex - I realize this is a pretty heavy refactor, but I hope it will be easier to modify and update going forward in this format. If you disagree, please feel free to let me know and I'll close this and just work off of my own fork. Thanks!

**Comment by rafrex** [comment]
Hi, sorry for the late response, was on vacation.

I would like to add more scroll options to this library, but at the same time want to keep it small and focused. What I'd like to do is add the optional prop `scrollFunction` which would be called with the element to scroll to, e.g. `scrollFunction(element)`, instead of using the built it `element.scrollIntoView()`. This would allow the use of any scroll function (including `jump`) while not adding any additional dependencies.

In looking at your code, it seems like your scroll functionality could be refactored out and provided as a `scrollFunction` prop.

What do you think of this idea? I'd be happy to accept a PR adding the `scrollFunction` prop.

**Comment by jpbufe3** [comment]
No worries. I think that's a great idea! I'll refactor this to handle that. Thanks.

**Comment by rafrex** [comment]
Great, I look forward to your updated PR. Also, if no `scrollFunction` prop is provided, then still use the default `element.scrollIntoView()`.

**Comment by jpbufe3** [comment]
@rafrex - please take another look when you get a chance

**Comment by rafrex** [comment]
Thanks for the update. Tracking the `hashFragment`, `observer`, and `asyncTimerID` need to be singletons, and not per instance. Since the scroll can be async, you want only the last clicked on `HashLink` to be scrolled to, otherwise the edge case where the page jumps to multiple positions after multiple clicks comes into play - and it's not needed (and wastes memory) to set more than one `observer`. I don't think it needs to become a class either, as it doesn't require any state.

The changes required from my original code I think are pretty minimal. If you use props/defaultProps to set the `scrollFn`, then all you need to do is set it as a singleton global to the file (note that because MutationObserver requires the function to be set when it is created, and not each time it observes, closures are required to pass variables to the function, hence the file globals):
```js
let scrollFn = null;

// in HashLink
if (hashFragment !== '') {
  scrollFn = props.scrollFn;
  hashLinkScroll();
} 

// in getElAndScroll
scrollFn(element);
```

I know this doesn't use your original code, but I think this is the direction I'd like to go, however, if there is something I've missed that makes this not a good solution, please let me know. I'd be happy to take a PR if you want to implement it, but if not no worries, I'm happy to do it at some point.

**Comment by jpbufe3** [comment]
okay. I see what you're getting at. I was trying to avoid globals if possible. this makes me think that all of this logic should just be a global observer that handles the scrolling anytime the hash changes, including on page load (which I realize is currently out of scope for this project). what do you think? would it be worthwhile making that? I'll go ahead and make the changes for this in the meantime anyway, but it might be a helpful package to make this more consistent throughout an app.

**Comment by rafrex** [comment]
The issue with a global observer is that when someone click's a link to `#someHash` which scrolls the page, then scrolls back to the link and clicks it again, the hash won't change, but the page should still scroll.

For scrolling on page load, the bowser will take care of it if the element is rendered initially (not created after an async data load). For the async case, I'd be inclined to accept a `scrollNow` prop, that when true calls `hashLinkScroll()`. If you want to implement this too, great! I think it can be accomplished with minimal change to the existing code.

**Comment by rafrex** [comment]
I implemented a custom scroll function in https://github.com/rafrex/react-router-hash-link/pull/16

**Pull request closed without merging**
